// src/cli/commands/init.mjs
// Initialize Swynx in a project - sets up CI workflow and config

import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Template paths
const TEMPLATES_DIR = join(__dirname, '../../..', 'templates/ci');

const GITHUB_WORKFLOW_TEMPLATE = `# .github/workflows/swynx.yml
# Swynx - Code Quality & Security Gate
# Generated by: swynx init
#
# QUICK START:
# 1. Add repository secrets: PEER_LICENSE and PEER_EMAIL
# 2. Uncomment the options you need below
# 3. Commit and push

name: Swynx

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  swynx:
    name: Code Quality Gate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Swynx
        run: |
          curl -sL https://github.com/AshOynk/swynx/releases/latest/download/swynx-linux-x64 -o swynx
          chmod +x swynx

      - name: Run Scan
        env:
          PEER_LICENSE: \${{ secrets.PEER_LICENSE }}
          PEER_EMAIL: \${{ secrets.PEER_EMAIL }}
          # SLACK_WEBHOOK: \${{ secrets.SLACK_WEBHOOK }}
        run: |
          ./swynx scan . --ci \\
            --key \$PEER_LICENSE \\
            --email \$PEER_EMAIL \\
            --github-annotations \\
            --github-summary
            #
            # ─── Output Options ───────────────────────────────────
            # --output json \\
            # --file scan-results.json \\
            # --config .swynx.json \\
            #
            # ─── Failure Threshold ────────────────────────────────
            # --fail-on-waste 20 \\
            #
            # ─── Cost Calculation ─────────────────────────────────
            # --currency GBP \\
            # --monthly-loads 10000 \\
            # --bandwidth-cost 0.08 \\
            # --cache-hit-rate 0.80 \\
            # --storage-cost 0.023 \\
            # --developer-rate 75 \\
            # --co2-per-gb 0.5 \\
            # --cost-mode served \\
            #
            # ─── Notifications ────────────────────────────────────
            # --slack-webhook \$SLACK_WEBHOOK \\
            #
            # ─── AI Integration ────────────────────────────────────
            # --ai-prompt \\

      # ─────────────────────────────────────────────────────────────
      # QUALITY GATE - Uncomment to enforce thresholds
      # ─────────────────────────────────────────────────────────────
      # - name: Quality Gate
      #   run: |
      #     ./swynx check \\
      #       --max-critical-vulnerabilities 0 \\
      #       --max-high-vulnerabilities 0
      #       #
      #       # ─── Security ───────────────────────────────────────
      #       # --max-exploitable-vulnerabilities 0 \\
      #       #
      #       # ─── Code Quality ───────────────────────────────────
      #       # --max-unused-deps 5 \\
      #       # --max-dead-code-percent 10 \\
      #       # --max-dead-files 3 \\
      #       # --max-waste-mb 50 \\
      #       #
      #       # ─── Dependencies ───────────────────────────────────
      #       # --max-outdated-major 5 \\
      #       # --max-outdated-critical 0 \\
      #       #
      #       # ─── License Compliance ─────────────────────────────
      #       # --require-license-compliance \\
      #       #
      #       # ─── Output ─────────────────────────────────────────
      #       # --json \\
      #       # --quiet \\

      # ─────────────────────────────────────────────────────────────
      # ARTIFACTS - Uncomment to save scan results
      # ─────────────────────────────────────────────────────────────
      # - name: Upload Scan Results
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: swynx-results
      #     path: scan-results.json
`;

const GITLAB_CI_TEMPLATE = `# .gitlab-ci.yml
# Swynx - Code Quality & Security Gate
# Generated by: swynx init
#
# QUICK START:
# 1. Add CI/CD variables: PEER_LICENSE and PEER_EMAIL
# 2. Uncomment the options you need below
# 3. Commit and push

variables:
  PEER_LICENSE: \${PEER_LICENSE}
  PEER_EMAIL: \${PEER_EMAIL}
  # SLACK_WEBHOOK: \${SLACK_WEBHOOK}

swynx:
  stage: test
  image: ubuntu:latest
  script:
    - apt-get update && apt-get install -y curl
    - curl -sL https://github.com/AshOynk/swynx/releases/latest/download/swynx-linux-x64 -o swynx
    - chmod +x swynx
    - |
      ./swynx scan . --ci \\
        --key $PEER_LICENSE \\
        --email $PEER_EMAIL \\
        --gitlab-codequality gl-code-quality-report.json
        #
        # ─── Output Options ───────────────────────────────────
        # --output json \\
        # --file scan-results.json \\
        # --config .swynx.json \\
        #
        # ─── Failure Threshold ────────────────────────────────
        # --fail-on-waste 20 \\
        #
        # ─── Cost Calculation ─────────────────────────────────
        # --currency GBP \\
        # --monthly-loads 10000 \\
        # --bandwidth-cost 0.08 \\
        # --cache-hit-rate 0.80 \\
        # --storage-cost 0.023 \\
        # --developer-rate 75 \\
        # --co2-per-gb 0.5 \\
        # --cost-mode served \\
        #
        # ─── Notifications ────────────────────────────────────
        # --slack-webhook $SLACK_WEBHOOK \\
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    # paths:
    #   - scan-results.json
    expire_in: 1 week
  only:
    - merge_requests
    - main
    - master

# ─────────────────────────────────────────────────────────────
# QUALITY GATE - Uncomment to enforce thresholds
# ─────────────────────────────────────────────────────────────
# swynx-gate:
#   stage: test
#   image: ubuntu:latest
#   needs: [swynx]
#   script:
#     - curl -sL https://github.com/AshOynk/swynx/releases/latest/download/swynx-linux-x64 -o swynx
#     - chmod +x swynx
#     - |
#       ./swynx check \\
#         --max-critical-vulnerabilities 0 \\
#         --max-high-vulnerabilities 0
#         #
#         # ─── Security ───────────────────────────────────────
#         # --max-exploitable-vulnerabilities 0 \\
#         #
#         # ─── Code Quality ───────────────────────────────────
#         # --max-unused-deps 5 \\
#         # --max-dead-code-percent 10 \\
#         # --max-dead-files 3 \\
#         # --max-waste-mb 50 \\
#         #
#         # ─── Dependencies ───────────────────────────────────
#         # --max-outdated-major 5 \\
#         # --max-outdated-critical 0 \\
#         #
#         # ─── License Compliance ─────────────────────────────
#         # --require-license-compliance \\
#   only:
#     - merge_requests
#     - main
#     - master
`;

const CONFIG_TEMPLATE = `{
  "version": "1.0",
  "thresholds": {
    "maxCriticalVulnerabilities": 0,
    "maxHighVulnerabilities": 0,
    "maxDeadCodePercent": 15,
    "failOnRestrictiveLicense": false,
    "failOnUnknownLicense": false
  },
  "exclude": [
    "node_modules",
    "dist",
    "build",
    ".git",
    "coverage",
    "**/*.test.js",
    "**/*.spec.js"
  ],
  "costs": {
    "currency": "GBP",
    "monthlyPageLoads": 10000,
    "developerHourlyRate": 75
  }
}
`;

/**
 * Initialize Swynx in a project
 */
export async function initCommand(projectPath = '.', options = {}) {
  const targetPath = projectPath === '.' ? process.cwd() : projectPath;
  const results = { created: [], skipped: [], errors: [] };

  console.log('');
  console.log('🔧 Initializing Swynx...');
  console.log('');

  // Detect CI platform
  const hasGitHub = existsSync(join(targetPath, '.git')) || existsSync(join(targetPath, '.github'));
  const hasGitLab = existsSync(join(targetPath, '.gitlab-ci.yml'));

  // Create GitHub workflow if requested or detected
  if (options.github || (!options.gitlab && hasGitHub)) {
    const workflowDir = join(targetPath, '.github/workflows');
    const workflowFile = join(workflowDir, 'swynx.yml');

    if (existsSync(workflowFile) && !options.force) {
      results.skipped.push('.github/workflows/swynx.yml (already exists)');
    } else {
      try {
        mkdirSync(workflowDir, { recursive: true });
        writeFileSync(workflowFile, GITHUB_WORKFLOW_TEMPLATE);
        results.created.push('.github/workflows/swynx.yml');
      } catch (e) {
        results.errors.push(`Failed to create GitHub workflow: ${e.message}`);
      }
    }
  }

  // Create GitLab CI if requested
  if (options.gitlab) {
    const gitlabFile = join(targetPath, '.gitlab-ci.yml');

    if (existsSync(gitlabFile) && !options.force) {
      results.skipped.push('.gitlab-ci.yml (already exists)');
    } else {
      try {
        // If file exists, we need to append rather than overwrite
        if (existsSync(gitlabFile)) {
          const existing = readFileSync(gitlabFile, 'utf-8');
          if (!existing.includes('swynx')) {
            writeFileSync(gitlabFile, existing + '\n' + GITLAB_CI_TEMPLATE);
            results.created.push('.gitlab-ci.yml (appended)');
          } else {
            results.skipped.push('.gitlab-ci.yml (swynx already configured)');
          }
        } else {
          writeFileSync(gitlabFile, GITLAB_CI_TEMPLATE);
          results.created.push('.gitlab-ci.yml');
        }
      } catch (e) {
        results.errors.push(`Failed to create GitLab CI: ${e.message}`);
      }
    }
  }

  // Create config file if requested
  if (options.config) {
    const configFile = join(targetPath, '.swynx.json');

    if (existsSync(configFile) && !options.force) {
      results.skipped.push('.swynx.json (already exists)');
    } else {
      try {
        writeFileSync(configFile, CONFIG_TEMPLATE);
        results.created.push('.swynx.json');
      } catch (e) {
        results.errors.push(`Failed to create config: ${e.message}`);
      }
    }
  }

  // Output results
  if (results.created.length > 0) {
    console.log('✅ Created:');
    for (const file of results.created) {
      console.log(`   ${file}`);
    }
    console.log('');
  }

  if (results.skipped.length > 0) {
    console.log('⏭️  Skipped:');
    for (const file of results.skipped) {
      console.log(`   ${file}`);
    }
    console.log('');
  }

  if (results.errors.length > 0) {
    console.log('❌ Errors:');
    for (const err of results.errors) {
      console.log(`   ${err}`);
    }
    console.log('');
  }

  // Next steps
  console.log('📋 Next steps:');
  console.log('');

  if (results.created.some(f => f.includes('github'))) {
    console.log('   1. Add secrets to your GitHub repository:');
    console.log('      - PEER_LICENSE: Your license key');
    console.log('      - PEER_EMAIL: Your registered email');
    console.log('');
    console.log('      Go to: Settings → Secrets and variables → Actions → New repository secret');
    console.log('');
  }

  if (results.created.some(f => f.includes('gitlab'))) {
    console.log('   1. Add CI/CD variables to your GitLab project:');
    console.log('      - PEER_LICENSE: Your license key');
    console.log('      - PEER_EMAIL: Your registered email');
    console.log('');
    console.log('      Go to: Settings → CI/CD → Variables');
    console.log('');
  }

  console.log('   2. Commit and push your changes:');
  console.log('      git add .');
  console.log('      git commit -m "Add Swynx CI workflow"');
  console.log('      git push');
  console.log('');
  console.log('   3. Open a PR to see Swynx in action!');
  console.log('');

  return results;
}

/**
 * Register the init command with Commander
 */
export function registerInitCommand(program) {
  program
    .command('init [path]')
    .description('Initialize Swynx in a project')
    .option('--github', 'Create GitHub Actions workflow')
    .option('--gitlab', 'Create GitLab CI configuration')
    .option('--config', 'Create .swynx.json config file')
    .option('--force', 'Overwrite existing files')
    .option('--all', 'Create all files (workflow + config)')
    .action(async (path = '.', options) => {
      // If --all, enable everything
      if (options.all) {
        options.github = true;
        options.config = true;
      }

      // Default to GitHub if nothing specified
      if (!options.github && !options.gitlab) {
        options.github = true;
      }

      await initCommand(path, options);
    });
}

export default { initCommand, registerInitCommand };
